//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramacionAvanzada_Proyecto_G2_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservas()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int idReserva { get; set; }
        public int idHabitacion { get; set; }
        public long idUsuario { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public System.DateTime fechaEgreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
